### ISSUE TITLE
Regression in 2.1.4: 'WatchdogFileMonitor' object has no attribute '_emitters'

### ISSUE THREAD

**Issue by hyperknot** [gorakhargosh/watchdog#830]
2.1.4 terminates in 
```
AttributeError: 'WatchdogFileMonitor' object has no attribute '_emitters'
```

2.1.3 is OK.

Full trace:
```
Traceback (most recent call last):
  File "venv/bin/pserve", line 8, in <module>
    sys.exit(main())
  File "venv/lib/python3.7/site-packages/pyramid/scripts/pserve.py", line 34, in main
    return command.run()
  File "venv/lib/python3.7/site-packages/pyramid/scripts/pserve.py", line 250, in run
    ignore_files=self.ignore_files,
  File "venv/lib/python3.7/site-packages/hupper/reloader.py", line 489, in start_reloader
    return reloader.run()
  File "venv/lib/python3.7/site-packages/hupper/reloader.py", line 138, in run
    with self._setup_runtime():
  File "/Users/user/.pyenv/versions/3.7.10/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "venv/lib/python3.7/site-packages/hupper/reloader.py", line 179, in _setup_runtime
    with self._start_monitor():
  File "/Users/user/.pyenv/versions/3.7.10/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "venv/lib/python3.7/site-packages/hupper/reloader.py", line 209, in _start_monitor
    self.monitor.start()
  File "venv/lib/python3.7/site-packages/hupper/reloader.py", line 56, in start
    self.monitor.start()
  File "venv/lib/python3.7/site-packages/watchdog/observers/api.py", line 254, in start
    for emitter in self._emitters.copy():
AttributeError: 'WatchdogFileMonitor' object has no attribute '_emitters'
```

**Comment by BoboTiG** [comment]
Could you share a minimal reproduction code please?

**Comment by hyperknot** [comment]
It's stock Pyramid framework's pserve command. Just try the starter project.

**Comment by BoboTiG** [comment]
OK I will have a look when I can, thanks for the report :)

**Comment by BoboTiG** [comment]
I reproduced and the regression was introduced with #814.

**Comment by BoboTiG** [comment]
[Watchdog 2.1.5](https://github.com/gorakhargosh/watchdog/releases/tag/v2.1.5) released with the fix :)

**Comment by hyperknot** [comment]
2.1.5 works perfectly, thanks for the quick fix!
